### ISSUE TITLE
About the updated Hook interface

### ISSUE THREAD

**Issue by senghoo** [qiniu/qmgo#203]
I noticed that PR #197, which was recently merged into the master branch, modified the Hook interface and added context as a parameter, which I think is a good improvement. 
However, I think this change may cause other projects that already use this library to inadvertently introduce bugs when upgrading related dependencies
This change will cause Hooks that should be called to not be called without any warning. and I think it is necessary to add a warning about this (keep checking if the original interface is satisfied) or maintain backward compatibility (call the original interface).
Finally, thank you for your excellent work as always!

**Comment by jiangz222** [comment]
Nice suggestion, we will do it ASAP, thanks!

**Comment by jiangz222** [comment]
After consideration, I think let everyone notice this change in the form of [release notes](https://github.com/qiniu/qmgo/releases/tag/v1.0.3), instead of making code compatibility.
Because if Qmgo implements hooks without context parameters at the same time, the burden of adding related functions to qmgo will become heavier.
At the same time, two versions hook (with or without context as parameter)  are supported at the same time, which has a certain understanding cost for users.
So I prefer to make it simple(fix context as parameter in hook), both to qmgo or users, in the early v1 version.
Therefore, users who upgrade to v1.0.3 and later versions, please add context parameters to your hook implementation:
